class Languages {
  static const Map<String, Map<String, String>> LANGUAGE = {
    'uz': {
      'mTitle': 'Aloqa operatori',
      'newsTitle': 'Yangiliklar',
      'internetTitle': 'Internet to`plamlar',
      'tariffTitle': 'Tarif to`plamlar',
      'minuteTitle': 'Daqiqa to`plamlar',
      'smsTitle': 'SMS to`plamlar',
      'ussdTitle': 'USSD to`plamlar',
      'servicesTitle': 'Xizmatlar',
      'telegram': 'Telegram kanal',
      'contact': 'Biz bilan aloqa',
      'language': 'Tilni o’zgartirish',
      'speed': 'Internet tezligini o`lchash',
      'rating': 'Baholash',
      'aboutUs': 'Biz haqimizda',
      'thelab': ' - tomonidan ishlab chiqildi.',
      'aboutText': 'Dastur "thelab" tomonidan ishlab chiqildi.',
      'webSite': 'Veb-sahifa',
      'contactUs': 'Dasturchilar bilan bog`lanish',
      'ussdText': 'O`tish kodi: ',
      'subscriptionFee': 'Abonent to`lovi:',
      'internetPack': 'Internet-trafik hajmi:',
      'internetPackD': 'Internet-trafik muddati:',
      'activateBtn': 'AKTIVLASHTIRISH',
      'errorTitle': 'Internet bilan aloqa yo`q.',
      'errorBtn': 'Birozdan so`ng urinib ko`ring.',
      'discriptionShort': 'Qisqacha: ',
      'loadingText': 'Yuklanmoqda...',
      'accountTitle': 'Shaxsiy sahifa',
      'shareText': 'Men tavsiya qilaman: mobil USSD kodlari ',
    },
    'kk': {
      'mTitle': 'Алоқа оператори',
      'newsTitle': 'Янгиликлар',
      'internetTitle': 'Интернет тўпламлар',
      'tariffTitle': 'Тариф тўпламлар',
      'minuteTitle': 'Дақиқа тўпламлар',
      'smsTitle': 'СМС тўпламлар',
      'ussdTitle': 'USSD тўпламлар',
      'servicesTitle': 'Хизматлар',
      'telegram': 'Телеграм канал',
      'contact': 'Биз билан алоқа',
      'language': 'Тилни ўзгартириш',
      'speed': 'Интернет тезлигини ўлчаш',
      'rating': 'Баҳолаш',
      'aboutUs': 'Биз ҳақимизда',
      'thelab': ' - томонидан ишлаб чиқилди.',
      'aboutText': 'Дастур "thelab" томонидан ишлаб чиқилди',
      'webSite': 'Веб-саҳифа',
      'contactUs': 'Дастурчилар билан боғланиш',
      'ussdText': 'Ўтиш коди: ',
      'subscriptionFee': 'Абонент тўлови:',
      'internetPack': 'Интернет-трафик ҳажми:',
      'internetPackD': 'Интернет-трафик муддати:',
      'activateBtn': 'АКТИВЛАШТИРИШ',
      'errorTitle': 'Интернет билан алоқа йўқ',
      'errorBtn': 'Бироздан сўнг уриниб кўринг',
      'discriptionShort': 'Қисқача: ',
      'loadingText': 'Юкланмоқда...',
      'accountTitle': 'Шахсий саҳифа',
      'shareText': 'Мен тавсия қиламан: мобил USSD кодлари ',
    },
    'ru': {
      'mTitle': 'Оператор',
      'newsTitle': 'Новости',
      'internetTitle': 'Интернет-пакеты',
      'tariffTitle': 'Тарифные планы',
      'minuteTitle': 'Пакеты минут',
      'smsTitle': 'SMS-пакеты',
      'ussdTitle': 'USSD-пакеты',
      'servicesTitle': 'Сервисы',
      'telegram': 'Телеграм канал',
      'contact': 'Связаться с нами',
      'language': 'Изменить язык',
      'speed': 'Скорость интернета',
      'rating': 'Оцените нас',
      'aboutUs': 'О нас',
      'thelab': 'Разработчик ',
      'aboutText': 'Приложение разработано командой "thelab".',
      'webSite': 'Веб страница:',
      'contactUs': 'Связаться с разработчиками:',
      'ussdText': 'Код доступа: ',
      'subscriptionFee': 'Абонентская плата:',
      'internetPack': 'Объем интернет-трафика:',
      'internetPackD': 'Срок действия:',
      'activateBtn': 'АКТИВИРОВАТЬ',
      'errorTitle': 'Нет соединения с интернетом.',
      'errorBtn': 'Попробуйте позже.',
      'discriptionShort': 'Коротко: ',
      'loadingText': 'Загружаются...',
      'accountTitle': 'Персональная страница',
      'shareText': 'Я рекомендую: мобильные USSD запросы ',
    },
  };
}
